#!/bin/csh
echo -n > index.js
cat jquery-1.3.2.js  >> index.js
cat jquery.validator.js  >> index.js
cat jquery.timers.js  >> index.js
cat jquery.form.js >> index.js
cat application.js >> index.js
cat customize.js >> index.js
cat swfobject.js >> index.js
cat md5.js >> index.js
php php/example-file.php
cp index.js ../js/index.js
